### ISSUE TITLE
Bug: Labels persist/duplicate over images when using arrow keys to switch

### ISSUE THREAD

**Issue by Neuron1c** [stonethree/s3label#23]
When labelling an image and then using the arrow keys to switch to the next image causes the labels to remain on the screen unless there is already label information available on the image. Issue happens consistently and is easily reproducible.

**Comment by shaunirwin** [comment]
Simone and I had a quick glance at this. Looks like one or two changes are required to the setting and fetching of the labels from the database (in the DrawingCanvas.vue file). Will confirm soon.
