### ISSUE TITLE
Bug: deleting last label on an image is non-persistent

### ISSUE THREAD

**Issue by RF5** [stonethree/s3label#24]
Problem: 
When annotating/labeling an image, deleting a label when that label is the last one on the image causes the deletion to be non-permanent -- i.e switching to another part of the website and back to that image will reveal the deleted label remains present. This issue only is present for the last label, deleting the 2nd last or any other label when there are multiple labels present does not cause this bug to occur.

Reproduction: 
Open any image, create 1 label (or several and delete them until you have 1 left). Then select the last label, and hit the delete key. The label should disappear. Then switch to another image or part of the site and switch back. The deleted label should still be there.

**Comment by shaunirwin** [comment]
Thanks for logging the issue. I noticed it a while back too. Will investigate asap.
