### ISSUE TITLE
Input image filtering based on labeling state

### ISSUE THREAD

**Issue by emmerentia** [stonethree/s3label#44]
Allow user to filter on which images to see in the labeling task view.
Options are:
- ' ' - this is the default operational mode.
- 'user complete' - these are all the images that has labels and that the user has marked as complete.
- 'user incomplete' - these are all the images that has labels and that the user has not marked as complete yet.

Future options are:
- Approved
- Needs improvement

**Comment by shaunirwin** [comment]
Closed by #66
